# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.cache/wt [current_project]
set_property parent.project_path D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.0 [current_project]
set_property ip_repo_paths d:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0.xci
set_property is_locked true [get_files D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top axi_tft_0 -part xc7z020clg484-1 -mode out_of_context
rename_ref -prefix_all axi_tft_0_
write_checkpoint -noxdef axi_tft_0.dcp
catch { report_utilization -file axi_tft_0_utilization_synth.rpt -pb axi_tft_0_utilization_synth.pb }
if { [catch {
  write_verilog -force -mode synth_stub D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.runs/axi_tft_0_synth_1/axi_tft_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.runs/axi_tft_0_synth_1/axi_tft_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.runs/axi_tft_0_synth_1/axi_tft_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.runs/axi_tft_0_synth_1/axi_tft_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
add_files D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.runs/axi_tft_0_synth_1/axi_tft_0_stub.v -of_objects [get_files D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0.xci]
add_files D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.runs/axi_tft_0_synth_1/axi_tft_0_stub.vhdl -of_objects [get_files D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0.xci]
add_files D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.runs/axi_tft_0_synth_1/axi_tft_0_sim_netlist.v -of_objects [get_files D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0.xci]
add_files D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.runs/axi_tft_0_synth_1/axi_tft_0_sim_netlist.vhdl -of_objects [get_files D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0.xci]
add_files D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.runs/axi_tft_0_synth_1/axi_tft_0.dcp -of_objects [get_files D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0.xci]

if {[file isdir D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.ip_user_files/ip/axi_tft_0]} {
  catch { 
    file copy -force D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.runs/axi_tft_0_synth_1/axi_tft_0_sim_netlist.v D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.ip_user_files/ip/axi_tft_0
  }
}

if {[file isdir D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.ip_user_files/ip/axi_tft_0]} {
  catch { 
    file copy -force D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.runs/axi_tft_0_synth_1/axi_tft_0_sim_netlist.vhdl D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.ip_user_files/ip/axi_tft_0
  }
}

if {[file isdir D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.ip_user_files/ip/axi_tft_0]} {
  catch { 
    file copy -force D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.runs/axi_tft_0_synth_1/axi_tft_0_stub.v D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.ip_user_files/ip/axi_tft_0
  }
}

if {[file isdir D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.ip_user_files/ip/axi_tft_0]} {
  catch { 
    file copy -force D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.runs/axi_tft_0_synth_1/axi_tft_0_stub.vhdl D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.ip_user_files/ip/axi_tft_0
  }
}
