# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0.xci
# IP: The module: 'axi_tft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IPX: D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0.xcix
# IPX: The module: 'axi_tft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_tft_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_tft_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_tft_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0.xci
# IP: The module: 'axi_tft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IPX: D:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0.xcix
# IPX: The module: 'axi_tft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_tft_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_tft_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Developers_KIT/Zynq702/TFTLCD/AXI_TFT/axi_tft_0_example/axi_tft_0_example.srcs/sources_1/ip/axi_tft_0/axi_tft_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_tft_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
