#!/bin/bash -f
# Vivado (TM) v2015.4 (64-bit)
#
# Filename    : axi_tft_0.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Jan 09 19:37:00 +0900 2016
# IP Build 1412160 on Tue Nov 17 13:47:24 MST 2015 
#
# usage: axi_tft_0.sh [-help]
# usage: axi_tft_0.sh [-lib_map_path]
# usage: axi_tft_0.sh [-noclean_files]
# usage: axi_tft_0.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'axi_tft_0.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Script info
echo -e "axi_tft_0.sh - Script generated by export_simulation (Vivado v2015.4 (64-bit)-id)\n"

# Script usage
usage()
{
  msg="Usage: axi_tft_0.sh [-help]\n\
Usage: axi_tft_0.sh [-lib_map_path]\n\
Usage: axi_tft_0.sh [-reset_run]\n\
Usage: axi_tft_0.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

if [[ ($# == 1 ) && ($1 != "-lib_map_path" && $1 != "-noclean_files" && $1 != "-reset_run" && $1 != "-help" && $1 != "-h") ]]; then
  echo -e "ERROR: Unknown option specified '$1' (type \"./axi_tft_0.sh -help\" for more information)\n"
  exit 1
fi

if [[ ($1 == "-help" || $1 == "-h") ]]; then
  usage
fi

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./axi_tft_0.sh -help\" for more information)\n"
        exit 1
      fi
      # precompiled simulation library directory path
     create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
     create_lib_mappings $2
  esac

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Remove generated data from the previous run and re-create setup files/library mappings
reset_run()
{
  files_to_remove=(ucli.key axi_tft_0_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc axi_tft_0_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# Main steps
run()
{
  setup $1 $2
  compile
  elaborate
  simulate
}

# Create design library directory paths and define design library mappings in cds.lib
create_lib_mappings()
{
  libs=(axi_lite_ipif_v3_0_3 lib_cdc_v1_0_2 lib_pkg_v1_0_2 fifo_generator_v13_0_1 lib_fifo_v1_0_4 lib_srl_fifo_v1_0_2 axi_master_burst_v2_0_7 axi_tft_v2_1_11 xil_defaultlib)
  file="synopsys_sim.setup"
  dir="vcs"

  if [[ -e $file ]]; then
    rm -f $file
  fi

  if [[ -e $dir ]]; then
    rm -rf $dir
  fi

  touch $file
  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi
  incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
  echo $incl_ref >> $file

  for (( i=0; i<${#libs[*]}; i++ )); do
    lib="${libs[i]}"
    lib_dir="$dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
      mapping="$lib : $dir/$lib"
      echo $mapping >> $file
    fi
  done
}


# RUN_STEP: <compile>
compile()
{
  # Directory path for design sources and include directories (if any) wrt this path
  ref_dir="."
  # Command line options
  opts_ver="-full64 -timescale=1ps/1ps"
  opts_vhd="-full64"

  # Compile design files
  vhdlan -work axi_lite_ipif_v3_0_3 $opts_vhd \
    "$ref_dir/../../../ip/axi_tft_0/axi_lite_ipif_v3_0_3/hdl/src/vhdl/ipif_pkg.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_lite_ipif_v3_0_3/hdl/src/vhdl/pselect_f.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_lite_ipif_v3_0_3/hdl/src/vhdl/address_decoder.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_lite_ipif_v3_0_3/hdl/src/vhdl/slave_attachment.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_lite_ipif_v3_0_3/hdl/src/vhdl/axi_lite_ipif.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $opts_vhd \
    "$ref_dir/../../../ip/axi_tft_0/lib_cdc_v1_0_2/hdl/src/vhdl/cdc_sync.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $opts_vhd \
    "$ref_dir/../../../ip/axi_tft_0/lib_pkg_v1_0_2/hdl/src/vhdl/lib_pkg.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work fifo_generator_v13_0_1 $opts_vhd \
    "$ref_dir/../../../ip/axi_tft_0/fifo_generator_v13_0_1/simulation/fifo_generator_vhdl_beh.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/fifo_generator_v13_0_1/hdl/fifo_generator_v13_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_4 $opts_vhd \
    "$ref_dir/../../../ip/axi_tft_0/lib_fifo_v1_0_4/hdl/src/vhdl/async_fifo_fg.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/lib_fifo_v1_0_4/hdl/src/vhdl/sync_fifo_fg.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $opts_vhd \
    "$ref_dir/../../../ip/axi_tft_0/lib_srl_fifo_v1_0_2/hdl/src/vhdl/cntr_incr_decr_addn_f.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/lib_srl_fifo_v1_0_2/hdl/src/vhdl/dynshreg_f.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/lib_srl_fifo_v1_0_2/hdl/src/vhdl/srl_fifo_rbu_f.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/lib_srl_fifo_v1_0_2/hdl/src/vhdl/srl_fifo_f.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_master_burst_v2_0_7 $opts_vhd \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_wr_demux.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_strb_gen.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_rdmux.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_fifo.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_wr_status_cntl.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_wrdata_cntl.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_stbs_set.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_skid_buf.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_skid2mm_buf.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_rd_status_cntl.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_rddata_cntl.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_pcc.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_first_stb_offset.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_addr_cntl.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_wr_llink.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_reset.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_rd_wr_cntlr.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_rd_llink.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst_cmd_status.vhd" \
    "$ref_dir/../../../ip/axi_tft_0/axi_master_burst_v2_0_7/hdl/src/vhdl/axi_master_burst.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_tft_v2_1_11 $opts_ver +v2k \
    "$ref_dir/../../../ip/axi_tft_0/axi_tft_v2_1_11/hdl/src/verilog/axi_tft_v2_1_iic_init.v" \
    "$ref_dir/../../../ip/axi_tft_0/axi_tft_v2_1_11/hdl/src/verilog/axi_tft_v2_1_v_sync.v" \
    "$ref_dir/../../../ip/axi_tft_0/axi_tft_v2_1_11/hdl/src/verilog/axi_tft_v2_1_tft_interface.v" \
    "$ref_dir/../../../ip/axi_tft_0/axi_tft_v2_1_11/hdl/src/verilog/axi_tft_v2_1_slave_register.v" \
    "$ref_dir/../../../ip/axi_tft_0/axi_tft_v2_1_11/hdl/src/verilog/axi_tft_v2_1_line_buffer.v" \
    "$ref_dir/../../../ip/axi_tft_0/axi_tft_v2_1_11/hdl/src/verilog/axi_tft_v2_1_h_sync.v" \
    "$ref_dir/../../../ip/axi_tft_0/axi_tft_v2_1_11/hdl/src/verilog/axi_tft_v2_1_tft_controller.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_tft_v2_1_11 $opts_vhd \
    "$ref_dir/../../../ip/axi_tft_0/axi_tft_v2_1_11/hdl/src/vhdl/axi_tft.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../ip/axi_tft_0/sim/axi_tft_0.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $opts_ver +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"

  vcs $opts xil_defaultlib.axi_tft_0 xil_defaultlib.glbl -o axi_tft_0_simv
}

# RUN_STEP: <simulate>
simulate()
{
  opts="-ucli -licqueue -l simulate.log"

  ./axi_tft_0_simv $opts -do simulate.do
}
# Script usage
usage()
{
  msg="Usage: axi_tft_0.sh [-help]\n\
Usage: axi_tft_0.sh [-lib_map_path]\n\
Usage: axi_tft_0.sh [-reset_run]\n\
Usage: axi_tft_0.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}


# Launch script
run $1 $2
