#!/bin/bash -f
# Vivado (TM) v2015.4 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Jan 13 22:26:36 +0900 2016
# IP Build 1412160 on Tue Nov 17 13:47:24 MST 2015 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2015.4 (64-bit)-id)\n"

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

if [[ ($# == 1 ) && ($1 != "-lib_map_path" && $1 != "-noclean_files" && $1 != "-reset_run" && $1 != "-help" && $1 != "-h") ]]; then
  echo -e "ERROR: Unknown option specified '$1' (type \"./system.sh -help\" for more information)\n"
  exit 1
fi

if [[ ($1 == "-help" || $1 == "-h") ]]; then
  usage
fi

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      # precompiled simulation library directory path
     create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
     create_lib_mappings $2
  esac

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Remove generated data from the previous run and re-create setup files/library mappings
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# Main steps
run()
{
  setup $1 $2
  compile
  elaborate
  simulate
}

# Create design library directory paths and define design library mappings in cds.lib
create_lib_mappings()
{
  libs=(xil_defaultlib lib_pkg_v1_0_2 lib_cdc_v1_0_2 axi_lite_ipif_v3_0_3 interrupt_control_v3_1_3 axi_iic_v2_0_10 proc_sys_reset_v5_0_8 fifo_generator_v13_0_1 lib_fifo_v1_0_4 blk_mem_gen_v8_3_1 lib_bmg_v1_0_3 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_9 axi_vdma_v6_2_6 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_7 axi_data_fifo_v2_1_6 axi_crossbar_v2_1_8 axi_master_burst_v2_0_7 axi_tft_v2_1_11 axi_protocol_converter_v2_1_7)
  file="synopsys_sim.setup"
  dir="vcs"

  if [[ -e $file ]]; then
    rm -f $file
  fi

  if [[ -e $dir ]]; then
    rm -rf $dir
  fi

  touch $file
  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi
  incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
  echo $incl_ref >> $file

  for (( i=0; i<${#libs[*]}; i++ )); do
    lib="${libs[i]}"
    lib_dir="$dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
      mapping="$lib : $dir/$lib"
      echo $mapping >> $file
    fi
  done
}


# RUN_STEP: <compile>
compile()
{
  # Directory path for design sources and include directories (if any) wrt this path
  ref_dir="."
  # Command line options
  opts_ver="-full64 -timescale=1ps/1ps"
  opts_vhd="-full64"

  # Compile design files
  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_wr.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_rd.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_wr_4.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_rd_4.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_hp2_3.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_hp0_1.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_ssw_hp.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_sparse_mem.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_reg_map.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_ocm_mem.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_intr_wr_mem.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_intr_rd_mem.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_fmsw_gp.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_regc.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_ocmc.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_interconnect_model.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_gen_reset.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_gen_clock.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_ddrc.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_axi_slave.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_axi_master.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_afi_slave.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_processing_system7_bfm.v" \
    "$ref_dir/../../../bd/system/ip/system_sys_ps7_0/sim/system_sys_ps7_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $opts_vhd \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/lib_pkg_v1_0/hdl/src/vhdl/lib_pkg.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $opts_vhd \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/lib_cdc_v1_0/hdl/src/vhdl/cdc_sync.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_3 $opts_vhd \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/ipif_pkg.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/pselect_f.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/address_decoder.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/slave_attachment.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/axi_lite_ipif.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_3 $opts_vhd \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/interrupt_control_v3_1/hdl/src/vhdl/interrupt_control.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_0_10 $opts_vhd \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_iic_v2_0/hdl/src/vhdl/soft_reset.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_iic_v2_0/hdl/src/vhdl/srl_fifo.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_iic_v2_0/hdl/src/vhdl/upcnt_n.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_iic_v2_0/hdl/src/vhdl/shift8.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_iic_v2_0/hdl/src/vhdl/iic_pkg.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_iic_v2_0/hdl/src/vhdl/debounce.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_iic_v2_0/hdl/src/vhdl/reg_interface.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_iic_v2_0/hdl/src/vhdl/iic_control.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_iic_v2_0/hdl/src/vhdl/filter.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_iic_v2_0/hdl/src/vhdl/dynamic_master.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_iic_v2_0/hdl/src/vhdl/axi_ipif_ssp1.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_iic_v2_0/hdl/src/vhdl/iic.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_iic_v2_0/hdl/src/vhdl/axi_iic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/system/ip/system_axi_iic_main_0/sim/system_axi_iic_main_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/xlconcat_v2_1/xlconcat.v" \
    "$ref_dir/../../../bd/system/ip/system_sys_concat_intc_0/sim/system_sys_concat_intc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_8 $opts_vhd \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/upcnt_n.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/sequence_psr.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/lpf.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/proc_sys_reset.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/system/ip/system_sys_rstgen_0/sim/system_sys_rstgen_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/ad_rst.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/up_drp_cntrl.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/ad_mmcm_drp.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/up_axi.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/up_clkgen.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/axi_clkgen_v1_0/axi_clkgen.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_hdmi_clkgen_0/sim/system_axi_hdmi_clkgen_0.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/ad_csc_1_mul.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/ad_csc_1_add.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/ad_csc_1.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/ad_mem.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/ad_csc_RGB2CrYCb.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/ad_ss_444to422.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/up_xfer_cntrl.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/up_xfer_status.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/up_clock_mon.v" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/up_hdmi_tx.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/axi_hdmi_tx_v1_0/axi_hdmi_tx_vdma.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/axi_hdmi_tx_v1_0/axi_hdmi_tx_core.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/axi_hdmi_tx_v1_0/axi_hdmi_tx.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_hdmi_core_0/sim/system_axi_hdmi_core_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_0_1 $opts_vhd \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/fifo_generator_v13_0/simulation/fifo_generator_vhdl_beh.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/fifo_generator_v13_0/hdl/fifo_generator_v13_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_4 $opts_vhd \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/lib_fifo_v1_0/hdl/src/vhdl/async_fifo_fg.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/lib_fifo_v1_0/hdl/src/vhdl/sync_fifo_fg.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work blk_mem_gen_v8_3_1 $opts_vhd \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/blk_mem_gen_v8_3/simulation/blk_mem_gen_v8_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_bmg_v1_0_3 $opts_vhd \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/lib_bmg_v1_0/hdl/src/vhdl/blk_mem_gen_wrapper.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $opts_vhd \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/lib_srl_fifo_v1_0/hdl/src/vhdl/cntr_incr_decr_addn_f.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/lib_srl_fifo_v1_0/hdl/src/vhdl/dynshreg_f.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/lib_srl_fifo_v1_0/hdl/src/vhdl/srl_fifo_rbu_f.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/lib_srl_fifo_v1_0/hdl/src/vhdl/srl_fifo_f.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_9 $opts_vhd \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_reset.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_afifo_autord.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_sfifo_autord.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_fifo.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_cmd_status.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_scc.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_strb_gen2.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_pcc.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_addr_cntl.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_rdmux.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_rddata_cntl.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_rd_status_cntl.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_wr_demux.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_wrdata_cntl.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_wr_status_cntl.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_skid2mm_buf.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_skid_buf.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_rd_sf.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_wr_sf.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_stbs_set.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_stbs_set_nodre.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_ibttcc.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_indet_btt.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_dre_mux2_1_x_n.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_dre_mux4_1_x_n.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_dre_mux8_1_x_n.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_mm2s_dre.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_s2mm_dre.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_ms_strb_set.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_mssai_skid_buf.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_slice.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_s2mm_scatter.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_s2mm_realign.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_s2mm_basic_wrap.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_s2mm_omit_wrap.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_s2mm_full_wrap.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_mm2s_basic_wrap.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_mm2s_omit_wrap.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover_mm2s_full_wrap.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_datamover_v5_1/hdl/src/vhdl/axi_datamover.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_2_6 $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog/axi_vdma_v6_2_axis_infrastructure_v1_0_util_axis2vector.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog/axi_vdma_v6_2_axis_infrastructure_v1_0_util_vector2axis.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog/axi_vdma_v6_2_axis_register_slice_v1_0_axisc_register_slice.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog/axi_vdma_v6_2_axis_register_slice_v1_0_axis_register_slice.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog/axi_vdma_v6_2_axis_dwidth_converter_v1_0_axisc_upsizer.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog/axi_vdma_v6_2_axis_dwidth_converter_v1_0_axisc_downsizer.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog/axi_vdma_v6_2_axis_dwidth_converter_v1_0_axis_dwidth_converter.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_2_6 $opts_vhd \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_pkg.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_ftch_sm.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_ftch_pntr.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_ftch_cmdsts_if.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_ftch_mngr.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_afifo_autord.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_ftch_queue.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_ftch_noqueue.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_ftch_q_mngr.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_updt_cmdsts_if.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_updt_sm.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_updt_mngr.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_updt_queue.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_updt_noqueue.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_updt_q_mngr.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg_intrpt.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_sg.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_pkg.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_cdc.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_vid_cdc.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_sg_cdc.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_reset.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_rst_module.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_lite_if.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_register.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_regdirect.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_reg_mux.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_reg_module.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_reg_if.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_intrpt.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_sof_gen.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_skid_buf.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_sfifo.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_sfifo_autord.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_afifo_builtin.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_afifo.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_afifo_autord.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_mm2s_linebuf.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_s2mm_linebuf.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_blkmem.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_fsync_gen.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_vregister.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_vregister_64.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_sgregister.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_vaddrreg_mux.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_vaddrreg_mux_64.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_vidreg_module.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_vidreg_module_64.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_genlock_mux.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_greycoder.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_genlock_mngr.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_sg_if.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_sm.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_cmdsts_if.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_sts_mngr.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_mngr.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_mngr_64.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_mm2s_axis_dwidth_converter.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma_s2mm_axis_dwidth_converter.vhd" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/vhdl/axi_vdma.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/system/ip/system_axi_hdmi_dma_0/sim/system_axi_hdmi_dma_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/dma_fifo.vhd" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/axi_ctrlif.vhd" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/axi_streaming_dma_tx_fifo.vhd" \
    "$ref_dir/../../../../project_1.srcs/analogdevicelibrary/hdl/hdl-hdl_2014_r2/hdl-hdl_2014_r2/library/common/pl330_dma_fifo.vhd" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/axi_spdif_tx_v1_0/tx_package.vhd" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/axi_spdif_tx_v1_0/tx_encoder.vhd" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/axi_spdif_tx_v1_0/axi_spdif_tx.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_spdif_tx_core_0/sim/system_axi_spdif_tx_core_0.vhd" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/axi_i2s_adi_v1_0/i2s_rx.vhd" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/axi_i2s_adi_v1_0/i2s_tx.vhd" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/axi_i2s_adi_v1_0/i2s_clkgen.vhd" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/axi_i2s_adi_v1_0/fifo_synchronizer.vhd" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/common/axi_streaming_dma_rx_fifo.vhd" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/axi_i2s_adi_v1_0/i2s_controller.vhd" \
    "$ref_dir/../../../../project_1.srcs/sources_1/ipshared/analog.com/axi_i2s_adi_v1_0/axi_i2s_adi.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_i2s_adi_0_0/sim/system_axi_i2s_adi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/xlconstant_v1_1/xlconstant.v" \
    "$ref_dir/../../../bd/system/ip/system_vcc_0/sim/system_vcc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_and.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_and.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_or.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_or.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_command_fifo.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask_static.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask_static.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_static.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_static.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux_enc.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_nto1_mux.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axi2vector.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axic_srl_fifo.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_vector2axi.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_7 $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axic_register_slice.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axi_register_slice.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_6 $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_fifo.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_fifo_gen.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_srl_fifo.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_reg_srl_fifo.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_ndeep_srl.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axi_data_fifo.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_8 $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter_sasd.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_decoder.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_arbiter_resp.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar_sasd.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_decerr_slave.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_si_transactor.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_splitter.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_mux.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_router.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_axi_crossbar.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_master_burst_v2_0_7 $opts_vhd \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_wr_demux.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_strb_gen.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_rdmux.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_fifo.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_wr_status_cntl.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_wrdata_cntl.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_stbs_set.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_skid_buf.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_skid2mm_buf.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_rd_status_cntl.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_rddata_cntl.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_pcc.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_first_stb_offset.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_addr_cntl.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_wr_llink.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_reset.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_rd_wr_cntlr.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_rd_llink.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_cmd_status.vhd" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_tft_v2_1_11 $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_tft_v2_1/hdl/src/verilog/axi_tft_v2_1_iic_init.v" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_tft_v2_1/hdl/src/verilog/axi_tft_v2_1_v_sync.v" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_tft_v2_1/hdl/src/verilog/axi_tft_v2_1_tft_interface.v" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_tft_v2_1/hdl/src/verilog/axi_tft_v2_1_slave_register.v" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_tft_v2_1/hdl/src/verilog/axi_tft_v2_1_line_buffer.v" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_tft_v2_1/hdl/src/verilog/axi_tft_v2_1_h_sync.v" \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_tft_v2_1/hdl/src/verilog/axi_tft_v2_1_tft_controller.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_tft_v2_1_11 $opts_vhd \
    "$ref_dir/../../../bd/system/ipshared/xilinx.com/axi_tft_v2_1/hdl/src/vhdl/axi_tft.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/system/ip/system_axi_tft_0_2/sim/system_axi_tft_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_7 $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_a_axi3_conv.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axi3_conv.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axilite_conv.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_r_axi3_conv.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_w_axi3_conv.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b_downsizer.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_decerr_slave.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_simple_fifo.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_wrap_cmd.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_incr_cmd.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_wr_cmd_fsm.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_rd_cmd_fsm.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_cmd_translator.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_b_channel.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_r_channel.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_aw_channel.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_ar_channel.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s.v" \
    "$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axi_protocol_converter.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/axi_vdma_v6_2/hdl/src/verilog" +incdir+"$ref_dir/../../../../../../Hdmi_adi/project_1.ip_user_files/ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_1/sim/system_auto_pc_1.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_2/sim/system_auto_pc_2.v" \
    "$ref_dir/../../../bd/system/hdl/system.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $opts_ver +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  opts="-load "C:/Xilinx/Vivado/2015.4/lib/win64.o/libxil_vcs.dll:xilinx_register_systf" -full64 -debug_pp -t ps -licqueue -l elaborate.log"

  vcs $opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  opts="-ucli -licqueue -l simulate.log"

  ./system_simv $opts -do simulate.do
}
# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}


# Launch script
run $1 $2
